SELECT NNN FROM Phl1.DBF O_VYD, Phl2.DBF O_POR
 WHERE (O_VYD.NNN=O_POR.NNN) AND 
(O_VYD.PRBPOR IN (100100, 100200))
 AND
(O_POR.NOMPOR=1)
 AND
(O_POR.KOFSOS BETWEEN 3 AND 4)
 AND
(O_POR.VOZ BETWEEN 11 AND 20)
 AND
 (O_POR.POL='0.6')
